# Generated by Django 2.2.3 on 2019-07-30 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190730_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply',
            new_name='reply_to',
        ),
    ]
